services:
  qdrant:
    image: qdrant/qdrant:latest-unprivileged
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./tmp/qdrant_data:/qdrant/storage
    user: "1000"
  cache:
    container_name: cache 
    image: ko.local/semantic-cache-a8044edf3c2796d6a5951c230da20a70:latest
    ports:
      - 8080:8080
    depends_on:
      - qdrant
    env_file:
      - ./.env

configs:
  qdrant_config:
    content: |
      log_level: INFO