name: Publish

on:
  push:
    branches: ['main', 'develop']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.x'
      - uses: actions/checkout@v4

      - uses: ko-build/setup-ko@v0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: ko build
