name: Publish

on:
  push:
    branches: ['main', 'develop']

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.23.x'
      - uses: actions/checkout@v3

      - uses: ko-build/setup-ko@v0.6
        env:
          KO_DOCKER_REPO: ghcr.io/backland-labs/semantic-cache
      - run: ko build --platform=linux/arm64